### ISSUE TITLE
How many requests can this API handle?

### ISSUE THREAD

**Issue by GrantBirki** [Ewpratten/pihole-api#5]
Not an issue but a question on how much traffic this API can handle.

I am currently running PiHole on a Raspberry Pi 3B+ and wondering if anyone has experienced issues querying the API. I'm doing a `pihole.refresh()` once every second and wondering if this is too much. It seems to bog down after running for about 15 minutes or so. Wondering if anyone else has done testing and has any input. :)

**Comment by jaykepeters** [comment]
I might be wrong, but I am mostly sure that all of Pi-hole's API data is stored in memory, and not on the disk, so you won't be hurting anything there. Otherwise it would be some minimal network traffic happening, in terms of KB, not MB. If the admin interface is constantly updating the data at certain intervals using the API, I would assume that you would be fine. In the next coming version of Pi-hole, the API will be even better and faster, and it will communicate on a socket with pihole-FTL. 

Any further questions or insight needed, please don't hesitate to ask me: jayke at jayke dot net

**Comment by GrantBirki** [comment]
I'll give you a follow as well! Thank you for the help. I've been experimenting with PiHole a lot more recently with some side projects and its actually performing quite well. I throttled back my script to hitting the API once every 5 seconds and its 100% fine. Thanks!
